import { McpServer } from "@modelcontextprotocol/server";
import { z } from "zod/v4";
import type { PersonalMcpPlugin, PersonalMcpPluginMetadata } from "../../core/plugin.js";
import { toolErrorResult, toolStructuredResult } from "../../core/tool-result.js";
import { JENKINS_CONFIG_FIELDS, loadJenkinsPluginConfig, type JenkinsPluginConfig } from "./config.js";
const META: PersonalMcpPluginMetadata = { id: "jenkins", displayName: "Jenkins", summary: "只读查询 Jenkins Job、构建配置和 Console Log。", category: { id: "ci", name: "持续集成", description: "查询构建状态与失败日志。" } };
const jobSchema = z.object({ job: z.string().trim().min(1).max(500) }); const buildSchema = jobSchema.extend({ build: z.number().int().nonnegative() }); const MAX_LOG = 50_000;
export function createJenkinsPlugin(options: { config?: JenkinsPluginConfig } = {}): PersonalMcpPlugin { const config = options.config ?? loadJenkinsPluginConfig(); return { ...META, tools: [{ name: "jenkins_get_job", title: "查询 Job", risk: "read-only", logging: { input: "full", output: "metadata" } }, { name: "jenkins_get_build", title: "查询构建", risk: "read-only", logging: { input: "full", output: "metadata" } }, { name: "jenkins_get_console_log", title: "查看 Console Log", risk: "read-only", logging: { input: "full", output: "metadata" } }], config: { fields: JENKINS_CONFIG_FIELDS }, checkHealth: async (signal) => { if (!config.url || !config.user || !config.token) return { state: "unconfigured" }; const r = await request(config, "/api/json", signal); return r.ok ? { state: "healthy" } : { state: "unhealthy", message: `Jenkins returned HTTP ${r.status}` }; }, createServer: () => createServer(config) }; }
async function request(c: JenkinsPluginConfig, path: string, signal?: AbortSignal) { return fetch(`${c.url}${path}`, { ...(signal === undefined ? {} : { signal }), headers: { authorization: `Basic ${Buffer.from(`${c.user}:${c.token}`).toString("base64")}`, accept: "application/json" } }); }
async function json(c: JenkinsPluginConfig, path: string) { const r = await request(c, path); if (!r.ok) throw new Error(`Jenkins returned HTTP ${r.status}`); const b = await r.json() as unknown; if (typeof b !== "object" || b === null || Array.isArray(b)) throw new Error("Jenkins returned invalid JSON"); return b as Record<string, unknown>; }
function createServer(c: JenkinsPluginConfig) { const s = new McpServer({ name: "jenkins-mcp-server", version: "0.1.0" }); s.registerTool("jenkins_get_job", { inputSchema: jobSchema }, async ({ job }) => { try { return toolStructuredResult(await json(c, `/job/${encodeURIComponent(job)}/api/json`)); } catch (e) { return toolErrorResult(e, { prefix: "Jenkins job query failed: " }); } }); s.registerTool("jenkins_get_build", { inputSchema: buildSchema }, async ({ job, build }) => { try { return toolStructuredResult(await json(c, `/job/${encodeURIComponent(job)}/${build}/api/json`)); } catch (e) { return toolErrorResult(e, { prefix: "Jenkins build query failed: " }); } }); s.registerTool("jenkins_get_console_log", { inputSchema: buildSchema }, async ({ job, build }) => { try { const r = await request(c, `/job/${encodeURIComponent(job)}/${build}/consoleText`); if (!r.ok) throw new Error(`Jenkins returned HTTP ${r.status}`); let text = await r.text(); const truncated = text.length > MAX_LOG; if (truncated) text = text.slice(-MAX_LOG); const hints = text.split("\n").filter(x => /error|exception|failed|failure/i.test(x)).slice(-20); return { content: [{ type: "text", text: JSON.stringify({ log: text, truncated, failureHints: hints }, null, 2) }] }; } catch (e) { return toolErrorResult(e, { prefix: "Jenkins console log query failed: " }); } }); return s; }
