export const ELASTICSEARCH_PLUGIN_ID = "elasticsearch";
export const ELASTICSEARCH_DEFAULT_PORT = 3106;

export const ELASTICSEARCH_DEFAULT_REQUEST_TIMEOUT_MS = 10_000;
export const ELASTICSEARCH_MIN_REQUEST_TIMEOUT_MS = 100;
export const ELASTICSEARCH_MAX_REQUEST_TIMEOUT_MS = 120_000;

export const ELASTICSEARCH_DEFAULT_MAX_HITS = 100;
export const ELASTICSEARCH_HARD_MAX_HITS = 1_000;
export const ELASTICSEARCH_DEFAULT_SEARCH_SIZE = 10;
export const ELASTICSEARCH_MAX_SAMPLE_SIZE = 5;
export const ELASTICSEARCH_DEFAULT_LIST_LIMIT = 50;
export const ELASTICSEARCH_MAX_LIST_LIMIT = 200;
export const ELASTICSEARCH_DEFAULT_MAX_FIELDS = 200;
export const ELASTICSEARCH_HARD_MAX_FIELDS = 1_000;

export const ELASTICSEARCH_DEFAULT_MAX_RESPONSE_BYTES = 1024 * 1024;
export const ELASTICSEARCH_MIN_RESPONSE_BYTES = 16 * 1024;
export const ELASTICSEARCH_MAX_RESPONSE_BYTES = 4 * 1024 * 1024;
export const ELASTICSEARCH_MAX_INDEX_EXPRESSION_LENGTH = 1_024;
